language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '7'
branches:
  except:
  - "/^v\\\\d+\\\\.\\\\d+\\\\.\\\\d+$/"
env:
  global:
    secure: sAS4pqLXJ2YOa82IMfM4kIehlK8oI4+olixBAkuJX+MqDxaPACnZqsQN0EkkePmMkoHRLTMGFy4+Mr8TiivnzcDSurGKoU4XajfkM6+aZQ0/S2F/LvJg5p4EsDvUUUOUd9sbjgo0eTPUAkpV4m7gRGLIZIbpCkjjfBPFKHUV+S1g3TOJ8obiJ8w9GN5CbFf/0PWIEtnWpg8wTP3O696tYiFBvNLjnKTRrxqOZwz43TyohRCSroXBNMZrzb1r9b9+rBt4EQibkEG2Q9m5DzhoaqdkUCg+qNaX2ufxuou9Ax/aMyb+8FRr+k+vnoeZzdKvK2xexgbxaaT3yG2POoV1YVzZ6blD7QhDweY7zBGyaQ1FIoqLbQkq7oqRvRXsSON1YZUfVKnspgTtk0HYA0p1pqUSfxWvOP+UWJ6TqZ8duHbmQDZWn4ufmg4AgiLQgaOUbrHgpdhD5ygu58WF6f+Qa9Z4ooOTJcvcmtWRV1MkOxGs5R4CwRlA3Ti9HNWVO9+V5I51EFAOpHy5yGdPfPxPRimNR8Dn5oyzOiuyEg5ICzVHOpQdgcDxLbWa4xTqklhq1uJqNyncz6V4xLhFaZlGwbMcGrabt7hEFk3mNpU15iN8Xq0rU3Qbnogcnk7Fi6KUVd5N7lLYQ3FHvQ8HVJruDWm4HjREgWcgXOFpOligIMo=
